//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid BaseAttck = new Guid("f8302355-e2b6-4b15-8f31-cdb656017bf3");
		public static readonly Guid BaseEnemy = new Guid("b733226d-9e53-4c8f-be29-f8abc9712f69");
		public static readonly Guid BaseEnemyScan = new Guid("fec13c95-8eac-47d6-9475-bca0b4de0018");
		public static readonly Guid BullAI = new Guid("ba617324-be08-4f7f-924d-7597bbf3ad42");
		public static readonly Guid FlamerAI = new Guid("c2f7f769-1996-4d97-9479-77dcaba7e68b");
		public static readonly Guid Heal = new Guid("ce72fe61-d981-4271-aa01-40c6bbb20512");
		public static readonly Guid HealerAI = new Guid("6415ac96-54f2-405f-851d-aa2e3d6b1561");
		public static readonly Guid KamikazeEnemy = new Guid("d577944b-8970-4326-9f56-4493640e6fbe");
		public static readonly Guid SpyEnemy = new Guid("e6fc5f07-8ee4-4a75-9962-ce8dc82f8f7c");

    }
}
